[workspace]
resolver = "2"
members = ["projects/*"]
default-members = [
    "projects/glob-walker",
    "projects/glob-parser",
]
exclude = [
    "projects/.DS_Store",
]

[profile.release]
lto = true
panic = "abort"
